// Generated by CoffeeScript 1.9.3
(function() {
  var fields, gen_fields_list, generate_where_row, getID, selectrowsEventHandler;

  fields = ['user', 'time', 'type'];

  window.onload = function() {
    var container;
    container = document.getElementById('selectrows');
    container.innerHTML = generate_where_row(1);
    return container.addEventListener('click', selectrowsEventHandler, false);
  };

  getID = function(target) {
    return +target.id.split('_').slice(-1);
  };

  selectrowsEventHandler = function(event) {
    var classes, rows;
    classes = event.target.classList;
    rows = document.getElementById('selectrows');
    if (_.contains(classes, 'fa-minus')) {
      rows.removeChild(document.getElementById('fieldrow_' + getID(event.target)));
      if (!rows.hasChildNodes()) {
        return rows.innerHTML += generate_where_row(1);
      }
    } else if (_.contains(classes, 'fa-plus')) {
      return rows.innerHTML += generate_where_row(getID(document.getElementById('selectrows').lastChild) + 1);
    }
  };

  gen_fields_list = function() {
    return fields.join(', ');
  };

  generate_where_row = function(id) {
    return "<div class='fieldrow' id='fieldrow_" + id + "'>\n<span>\n    <div class='field'>\n        <input type='text' id='where_left_" + id + "' placeholder='Field' required />\n        <span class=\"fa fa-question-circle\">\n            <span>" + (gen_fields_list()) + "</span>\n        </span>\n        <label for='where_left_" + id + "'>Field</label>\n    </div>\n</span>\n<span>\n    <div class='field'>\n        <select required>\n            <option value=''>Operator</option>\n            <option value='='>is</option>\n            <option value='!'>is not</option>\n            <option value='<'>&lt;</option>\n            <option value='>'>&gt;</option>\n            <option value='~'>matches</option>\n        </select>\n        <label>Operator</label>\n    </div>\n</span>\n<span>\n    <div class='field'>\n        <input type='text' id='where_right_" + id + "' placeholder='Comparison' required />\n        <label for='where_right_${id}'>Comparison</label>\n    </div>\n</span>\n<span class=\"fa fa-minus\" id='where_remove_" + id + "'></span>\n<span class=\"fa fa-plus\" id='where_add_" + id + "'></span>\n</div>";
  };

}).call(this);
